/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppImagesRouteImport } from './routes/_app.images'
import { Route as AppMediaRouteImport } from './routes/_app.media'
import { Route as AppSetsRouteImport } from './routes/_app.sets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTagsRouteImport } from './routes/_app.tags'
import { Route as AppVideosRouteImport } from './routes/_app.videos'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiLibraryRouteImport } from './routes/api.library'
import { Route as AppSetsSetIdRouteImport } from './routes/_app.sets.$setId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiDriveWebhookRouteImport } from './routes/api.drive.webhook'
import { Route as ApiMediaIdRouteImport } from './routes/api.media.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsRoute = AppSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryRoute = ApiLibraryRouteImport.update({
  id: '/api/library',
  path: '/api/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetsSetIdRoute = AppSetsSetIdRouteImport.update({
  id: '/$setId',
  path: '/$setId',
  getParentRoute: () => AppSetsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveWebhookRoute = ApiDriveWebhookRouteImport.update({
  id: '/api/drive/webhook',
  path: '/api/drive/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/images': typeof AppImagesRoute
  '/media': typeof AppMediaRoute
  '/sets': typeof AppSetsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/videos': typeof AppVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/library': typeof ApiLibraryRoute
  '/sets/$setId': typeof AppSetsSetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/webhook': typeof ApiDriveWebhookRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/images': typeof AppImagesRoute
  '/media': typeof AppMediaRoute
  '/sets': typeof AppSetsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/tags': typeof AppTagsRoute
  '/videos': typeof AppVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/library': typeof ApiLibraryRoute
  '/sets/$setId': typeof AppSetsSetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/webhook': typeof ApiDriveWebhookRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/images': typeof AppImagesRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/sets': typeof AppSetsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/videos': typeof AppVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/api/library': typeof ApiLibraryRoute
  '/_app/sets/$setId': typeof AppSetsSetIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/drive/webhook': typeof ApiDriveWebhookRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/images'
    | '/media'
    | '/sets'
    | '/settings'
    | '/tags'
    | '/videos'
    | '/api/health'
    | '/api/library'
    | '/sets/$setId'
    | '/api/auth/$'
    | '/api/drive/webhook'
    | '/api/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/images'
    | '/media'
    | '/sets'
    | '/settings'
    | '/tags'
    | '/videos'
    | '/api/health'
    | '/api/library'
    | '/sets/$setId'
    | '/api/auth/$'
    | '/api/drive/webhook'
    | '/api/media/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/images'
    | '/_app/media'
    | '/_app/sets'
    | '/_app/settings'
    | '/_app/tags'
    | '/_app/videos'
    | '/api/health'
    | '/api/library'
    | '/_app/sets/$setId'
    | '/api/auth/$'
    | '/api/drive/webhook'
    | '/api/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLibraryRoute: typeof ApiLibraryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDriveWebhookRoute: typeof ApiDriveWebhookRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/images': {
      id: '/_app/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sets': {
      id: '/_app/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof AppSetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/videos': {
      id: '/_app/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library': {
      id: '/api/library'
      path: '/api/library'
      fullPath: '/api/library'
      preLoaderRoute: typeof ApiLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sets/$setId': {
      id: '/_app/sets/$setId'
      path: '/$setId'
      fullPath: '/sets/$setId'
      preLoaderRoute: typeof AppSetsSetIdRouteImport
      parentRoute: typeof AppSetsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/webhook': {
      id: '/api/drive/webhook'
      path: '/api/drive/webhook'
      fullPath: '/api/drive/webhook'
      preLoaderRoute: typeof ApiDriveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSetsRouteChildren {
  AppSetsSetIdRoute: typeof AppSetsSetIdRoute
}

const AppSetsRouteChildren: AppSetsRouteChildren = {
  AppSetsSetIdRoute: AppSetsSetIdRoute,
}

const AppSetsRouteWithChildren =
  AppSetsRoute._addFileChildren(AppSetsRouteChildren)

interface AppRouteChildren {
  AppImagesRoute: typeof AppImagesRoute
  AppMediaRoute: typeof AppMediaRoute
  AppSetsRoute: typeof AppSetsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppVideosRoute: typeof AppVideosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImagesRoute: AppImagesRoute,
  AppMediaRoute: AppMediaRoute,
  AppSetsRoute: AppSetsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTagsRoute: AppTagsRoute,
  AppVideosRoute: AppVideosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLibraryRoute: ApiLibraryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDriveWebhookRoute: ApiDriveWebhookRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
